// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

export const OTEL_INSTRUMENTATION_GENAI_MESSAGE_CONTENT_MAX_LENGTH =
  "OTEL_INSTRUMENTATION_GENAI_MESSAGE_CONTENT_MAX_LENGTH";
export const OTEL_INSTRUMENTATION_GENAI_MESSAGE_CONTENT_CAPTURE_STRATEGY =
  "OTEL_INSTRUMENTATION_GENAI_MESSAGE_CONTENT_CAPTURE_STRATEGY";
export const OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_STORAGE_BASE_PATH =
  "OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_STORAGE_BASE_PATH";
export const OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_UPLOAD_MODE =
  "OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_UPLOAD_MODE";
export const OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_DOWNLOAD_ENABLED =
  "OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_DOWNLOAD_ENABLED";
export const OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_DOWNLOAD_SSL_VERIFY =
  "OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_DOWNLOAD_SSL_VERIFY";
export const OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_AUDIO_CONVERSION_ENABLED =
  "OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_AUDIO_CONVERSION_ENABLED";
export const OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_LOCAL_FILE_ENABLED =
  "OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_LOCAL_FILE_ENABLED";
export const OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_ALLOWED_ROOT_PATHS =
  "OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_ALLOWED_ROOT_PATHS";
export const OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_UPLOADER =
  "OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_UPLOADER";
export const OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_PRE_UPLOADER =
  "OTEL_INSTRUMENTATION_GENAI_MULTIMODAL_PRE_UPLOADER";
